@hostname = localhost
@port = 44388
@host = {{hostname}}:{{port}}
@contentType = application/json

POST https://{{host}}/api/rentals
Content-Type: {{contentType}}

{
	"customerId": 23,
	"movieIds": [2,3]
}